// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRqvNgAKtOaaO3f4Pi0Ef_9Zm6CixaAi8',
    appId: '1:994383155820:web:83bb621dd1b792374bfe49',
    messagingSenderId: '994383155820',
    projectId: 'stpaul-anglican',
    authDomain: 'stpaul-anglican.firebaseapp.com',
    storageBucket: 'stpaul-anglican.appspot.com',
    measurementId: 'G-9WJFQ266GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd8JfeBjtcEddtXXjejHopDpYA1V7yTY4',
    appId: '1:994383155820:android:cce51523cf756ed44bfe49',
    messagingSenderId: '994383155820',
    projectId: 'stpaul-anglican',
    storageBucket: 'stpaul-anglican.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvCXlf9THsmK5_xkLnVMAe_3NuWSMbF-k',
    appId: '1:994383155820:ios:d20e4cd91b4c4cab4bfe49',
    messagingSenderId: '994383155820',
    projectId: 'stpaul-anglican',
    storageBucket: 'stpaul-anglican.appspot.com',
    iosClientId: '994383155820-vg6udbkeevhcr2oh8l5h1ohlhbbfe750.apps.googleusercontent.com',
    iosBundleId: 'stpaul',
  );
}
